M48
; DRILL file {KiCad (6.0.4)} date Thu 14 Apr 2022 06:16:01 PM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-14T18:16:01+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X107.7Y-73.5
X107.7Y-104.0
X146.5Y-73.5
X146.5Y-104.0
T0
M30
